"""
Settings of the system.
"""
PEER_EXPIRY = 5.0

WORKER_MCAST_GROUP = '224.1.1.1'
WORKER_MCAST_PORT = 4040
WORKER_MCAST_ADDR = (
    WORKER_MCAST_GROUP,
    WORKER_MCAST_PORT
)
WORKER_PING_SIZE = 12

